### ISSUE TITLE
Add Telescope plugin to NvPak config

### ISSUE THREAD

**Issue by MostafaMotahari** [Pakrohk-DotFiles/NvPak#28]
Telescope is a fuzzy finder plugin.
I think it is good to add it to the configs.

Github
https://github.com/nvim-telescope/telescope.nvim

**Comment by Pakrohk** [comment]
![Fuzzy Finder](https://user-images.githubusercontent.com/48873115/217238383-51c83389-ef78-414c-bdda-2896033ce389.png)

Will be added soon.

**Comment by Pakrohk** [comment]
Added to the project.

https://github.com/Pakrohk-DotFiles/NvPak/commit/6ed5075a7e7d7edb728da222bf86d5cb72c525ca
https://github.com/Pakrohk-DotFiles/NvPak/commit/e2037ab49fdcad4880e8d75f69c83a4cecdf9a61
