### ISSUE TITLE
Tabnine display priority is very low if LSP is active (so low that it is not even displayed)

### ISSUE THREAD

**Issue by Pakrohk** [Pakrohk-DotFiles/NvPak#38]
I really don't know how to solve this problem, if you can solve it please help the project with a pull request.

**Comment by ARS101** [comment]
But isn't that how it's supposed to work?
LSP results must be at the top because they're more relevant.

**Comment by Pakrohk** [comment]
> But isn't that how it's supposed to work?
LSP results must be at the top because they're more relevant.

> Also, how is it not displayed? Isn't the autocomplete menu scrollable?
I would like a picture of this issue here for others to see.

Yes, it is true that the LSP results should be at the highest level, but the Tabnine results should exactly be the next priority, but it is not there at all, and there is no display of the Tabnine outputs.

![image](https://user-images.githubusercontent.com/27810360/216793228-5d478ff6-71cd-427f-819e-d4d1067dba3c.png)

**Comment by Pakrohk** [comment]
> Is there any progress on this issue? Should we ask the devs for input?

This problem happened due to software sanctions and currently there is no solution (for Iranian users) unless ip change software is used.
