### ISSUE TITLE
Add a dashboard 

### ISSUE THREAD

**Issue by lorem10** [Pakrohk-DotFiles/NvPak#43]
### I want to contribute to the task of adding a dashboard.

As a suggestion, I can use [dashboard-nvim](https://github.com/glepnir/dashboard-nvim), but it need to telescope plugin.
So i will wait until the task is done in the panel, then I will send my PR

**Comment by Pakrohk** [comment]
Follow the path below to add this plugin to the project.
 1- Fork the project
 2- Create a branch with your name or the plugin you want to add.
 3- Send the request money and it will be checked.

Welcome to the nvpak team in advance.
Make sure that the most important things you must observe:
  1- Everything should be in its simplest form.
  2- Try to make the configuration easy to understand and change.
  3- If there is a shortcut key, define it in the bind file.

Telescope plugin is being added to the project, thank you for your follow up.
