### ISSUE TITLE
Add support for dart and flutter languages

### ISSUE THREAD

**Issue by Nooob-Student** [Pakrohk-DotFiles/NvPak#61]
Hello, I opened these issues
 https://github.com/flutter/flutter/issues/120451
 in Flutter GitHub and said it was a problem. I want you to check it and help if possible.

**Comment by Pakrohk** [comment]
I see and check.

**Comment by Pakrohk** [comment]
Dear friend @Nooob-Student you have to make a fork of nvpak and manually install flutter-tools in it.
Of course, we may soon add support for it officially to nvpak.
Thanks for your follow up.

**Comment by Pakrohk** [comment]
Check it out and let me know if there is a problem.

**Comment by lorem10** [comment]
I suggest that the support of flutter and special technologies like this should not be done in this repo and should be left to the users/contributors in other templates or forks.

**Comment by Pakrohk** [comment]
> I suggest that the support of flutter and special technologies like this should not be done in this repo and should be left to the users/contributors in other templates or forks.

The purpose of development of version 2.5.0 is to make NvPak more targeted, so until version 2.4.0 all extra plugins will be removed and syntax problems will be fixed.

**Comment by Pakrohk** [comment]
nvpak no longer officially supports flutter, as its purpose is to create a background for creating user settings, not to create a complete configuration for specific languages, but we will write the document in a modified way soon.
Somehow users have to learn how to add a new lsp to their configs.
